# Generated by Django 3.0.8 on 2020-08-24 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voe_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('name_lower', models.CharField(default='<django.db.models.fields.charfield>', max_length=200)),
                ('part_type', models.CharField(blank=True, default='Regular', max_length=20)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voe_projects.Project', to_field='uuid')),
            ],
            options={
                'unique_together': {('name_lower', 'project_id')},
            },
        ),
    ]
