# Generated by Django 3.0.8 on 2020-08-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voe_projects', '0001_initial'),
        ('voe_parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('labels', models.CharField(max_length=1000, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('remote_url', models.CharField(max_length=1000, null=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voe_parts.Part')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voe_projects.Project')),
            ],
        ),
    ]
