# Generated by Django 3.0.8 on 2020-09-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("azure_part_detections", "0014_partdetection_fps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partdetection", name="metrics_accuracy_threshold",
        ),
    ]
