#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"


if [ -z "${DBUSER}" ]; then
    base_postgres_image_default_user='postgres'
    export DBUSER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${DBUSER}:${DBPASS}@${DBHOST}:${DBPORT}/${DBNAME}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${DBNAME}",
        user="${DBUSER}",
        password="${DBPASS}",
        host="${DBHOST}",
        port="${DBPORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
