# Generated by Django 3.0.8 on 2020-08-24 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voe_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingIteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('performance', models.CharField(default='{}', max_length=2000)),
                ('models', models.FileField(null=True, upload_to='models')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voe_projects.Project', to_field='uuid')),
            ],
        ),
    ]
