# Generated by Django 3.0.8 on 2020-08-24 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voe_training_iterations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingiteration',
            old_name='models',
            new_name='result_model',
        ),
        migrations.AddField(
            model_name='trainingiteration',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
